// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function GetMethod():Promise<string>;

export function GetMethods():Promise<Array<api.HttpMethod>>;

export function SendRequest(arg1:api.Request):Promise<api.Response>;

export function SetMethod(arg1:string):Promise<void>;
