// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMethod() {
  return window['go']['api']['HttpV1']['GetMethod']();
}

export function GetMethods() {
  return window['go']['api']['HttpV1']['GetMethods']();
}

export function SendRequest(arg1) {
  return window['go']['api']['HttpV1']['SendRequest'](arg1);
}

export function SetMethod(arg1) {
  return window['go']['api']['HttpV1']['SetMethod'](arg1);
}
